### ISSUE TITLE
About Detailed Train Command.

### ISSUE THREAD

**Issue by intrepidLi** [chenchenygu/watermark-learnability#1]
Hello, could you please release an example about the detailed training commands?

For `train_logits_distill.py`, my command is such like 
``` sh
CUDA_VISIBLE_DEVICES=0,1,2,3 nohup torchrun --nproc_per_node=4 train_logits_distill.py \
--model_name_or_path /data3/MODELS/llama2-hf/llama-2-7b \
--dataset_name Skylion007/openwebtext \
--output_dir kgw_distill_res \
--num_train_epochs 1.0 \
--per_device_train_batch_size 1 \
--learning_rate 1e-5 \
--overwrite_output_dir true \
--do_train true \
--seed 42 \
--watermark_type kgw \
--gradient_accumulation_steps 4 \
--kgw_watermark_gamma 0.25 \
--kgw_watermark_delta 2.0 \
--streaming true \
--max_steps 10000 \
--save_steps 1000 \
--save_checkpoint_models false \
--bf16 true \
--argmax_watermark false \
--warmup_steps 500 \
--custom_cosine_lr_scheduler true \
--cache_dir ./datasets \
--lr_scheduler_type cosine > ./trainLog3.log &
```

But it will cause "CUDA Out of Memory" Error. 

My environment is as below:
python == 3.11.5
4 * A100-SXM4-80GB
CUDA VERSION: 12.2
Ubuntu 20.04.4 LTS

**Comment by chenchenygu** [comment]
Sure, here is the command we used to fit Llama 2 7B on 4 A100s:
 ```
torchrun --nproc_per_node=4 train_logits_distill.py \
    --model_name_or_path meta-llama/Llama-2-7b-hf/ \
    --dataset_name openwebtext \
    --streaming \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --do_train \
    --max_steps 5000 \
    --logging_steps 1 \
    --output_dir [OUTPUT_DIR] \
    --learning_rate 1e-5 \
    --custom_cosine_lr_scheduler False \
    --lr_scheduler_type "cosine" \
    --warmup_steps 500 \
    --block_size 512 \
    --save_steps 1000 \
    --save_total_limit 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap "LlamaDecoderLayer" \
    --tf32 True \
    --bf16 True \
    --gradient_checkpointing \
    --watermark_type "kgw" \
    --kgw_watermark_gamma 0.25 \
    --kgw_watermark_delta 2.0 \
    --argmax_watermark False; \
```
Also, we are working on cleaning up the code and releasing scripts and documentation for the camera ready!

**Comment by intrepidLi** [comment]
Thank you for your reply! My problem has been solved.

**Comment by yeahjack** [comment]
> Sure, here is the command we used to fit Llama 2 7B on 4 A100s:
> 
> ```
> torchrun --nproc_per_node=4 train_logits_distill.py \
>    --model_name_or_path meta-llama/Llama-2-7b-hf/ \
>    --dataset_name openwebtext \
>    --streaming \
>    --per_device_train_batch_size 16 \
>    --gradient_accumulation_steps 1 \
>    --do_train \
>    --max_steps 5000 \
>    --logging_steps 1 \
>    --output_dir [OUTPUT_DIR] \
>    --learning_rate 1e-5 \
>    --custom_cosine_lr_scheduler False \
>    --lr_scheduler_type "cosine" \
>    --warmup_steps 500 \
>    --block_size 512 \
>    --save_steps 1000 \
>    --save_total_limit 1 \
>    --fsdp "full_shard auto_wrap" \
>    --fsdp_transformer_layer_cls_to_wrap "LlamaDecoderLayer" \
>    --tf32 True \
>    --bf16 True \
>    --gradient_checkpointing \
>    --watermark_type "kgw" \
>    --kgw_watermark_gamma 0.25 \
>    --kgw_watermark_delta 2.0 \
>    --argmax_watermark False; \
> ```
> 
> Also, we are working on cleaning up the code and releasing scripts and documentation for the camera ready!

Dear developer,

When I am using this script, it turns to me that `AttributeError: 'WatermarkDistillTrainer' object has no attribute 'fsdp'`. More specifically, the error turns out to be:

```
Traceback (most recent call last):
  File "/home/yijiexu/watermark-learnability/train_logits_distill.py", line 1000, in <module>
    main()
  File "/home/yijiexu/watermark-learnability/train_logits_distill.py", line 921, in main
    trainer = WatermarkDistillTrainer(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yijiexu/watermark-learnability/train_logits_distill.py", line 388, in __init__
    self.teacher_model = self._fsdp_teacher_model(self.teacher_model)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yijiexu/watermark-learnability/train_logits_distill.py", line 489, in _fsdp_teacher_model
    if self.fsdp is not None:
       ^^^^^^^^^
AttributeError: 'WatermarkDistillTrainer' object has no attribute 'fsdp'
```

Would you happen to have any ideas on this error? Thank you for your suggestions!

**Comment by intrepidLi** [comment]
Hello, I haven't encountered this issue. `fsdp` is an attribute of the `Trainer` class. In the source code, `WatermarkDistillTrainer` inherits from the `Trainer` class, so normally the `WatermarkDistillTrainer` class should also have this attribute.

**Comment by yeahjack** [comment]
> Hello, I haven't encountered this issue. `fsdp` is an attribute of the `Trainer` class. In the source code, `WatermarkDistillTrainer` inherits from the `Trainer` class, so normally the `WatermarkDistillTrainer` class should also have this attribute.

I am wondering whether this problem arises from the version of `transformers`. Would you mind sharing your version? Currently, I am using version 4.40.0. Thanks!

**Comment by intrepidLi** [comment]
Hello, my `transformers` version is 4.29.2, `pytorch` version is 2.0.1+cu117.

**Comment by yeahjack** [comment]
> Hello, my `transformers` version is 4.29.2, `pytorch` version is 2.0.1+cu117.

Thanks, I tried to modify the code as follows:

```python
def _fsdp_teacher_model(self, model):
        if self.args.fsdp is not None:
            # PyTorch FSDP!
            from torch.distributed.fsdp.fully_sharded_data_parallel import CPUOffload
            from torch.distributed.fsdp.fully_sharded_data_parallel import FullyShardedDataParallel as FSDP
            from torch.distributed.fsdp.fully_sharded_data_parallel import MixedPrecision
            from torch.distributed.fsdp.wrap import size_based_auto_wrap_policy, transformer_auto_wrap_policy

            if FSDPOption.OFFLOAD in self.args.fsdp:
                cpu_offload = CPUOffload(offload_params=True)
            else:
                cpu_offload = CPUOffload(offload_params=False)

            auto_wrap_policy = None
            if FSDPOption.AUTO_WRAP in self.args.fsdp:
                if self.args.fsdp_min_num_params > 0:
                    auto_wrap_policy = functools.partial(
                        size_based_auto_wrap_policy,
                        min_num_params=self.args.fsdp_min_num_params)
                elif self.args.fsdp_transformer_layer_cls_to_wrap is not None:
                    transformer_cls_to_wrap = get_module_class_from_name(
                        model, self.args.fsdp_transformer_layer_cls_to_wrap)
                    if transformer_cls_to_wrap is None:
                        raise Exception(
                            "Could not find the transformer layer class to wrap in the model."
                        )
                    auto_wrap_policy = functools.partial(
                        transformer_auto_wrap_policy,
                        # Transformer layer class to wrap
                        transformer_layer_cls={transformer_cls_to_wrap},
                    )
            mixed_precision_policy = None
            dtype = None
            if self.args.fp16:
                dtype = torch.float16
            elif self.args.bf16:
                dtype = torch.bfloat16
            if dtype is not None:
                mixed_precision_policy = MixedPrecision(param_dtype=dtype,
                                                        reduce_dtype=dtype,
                                                        buffer_dtype=dtype)
            if type(model) != FSDP:
                # XXX: Breaking the self.model convention but I see no way around it for now.
                model = FSDP(
                    model,
                    sharding_strategy=torch.distributed.fsdp.api.ShardingStrategy.FULL_SHARD,
                    cpu_offload=cpu_offload,
                    auto_wrap_policy=auto_wrap_policy,
                    mixed_precision=mixed_precision_policy,
                    device_id=self.args.device,
                )
        return model
```

By doing this, I replaced `self.fsdp` with `self.args.fsdp` and directly set the sharding strategy as what is in your training code. Could you please help me determine whether this edit does change anything?

**Comment by yeahjack** [comment]
> Hello, my `transformers` version is 4.29.2, `pytorch` version is 2.0.1+cu117.

By the way, I am now entirely using your version of `pytorch` and `transformers`, but the same problem arises again. I am trying to understand why this happens...

Here is my relevant info:

```bash
❯ pip list | grep torch
torch                    2.0.1
torchaudio               2.0.2
torchvision              0.15.2
❯ micromamba list | grep pytorch     
  pytorch             2.0.1       py3.11_cuda11.7_cudnn8.5.0_0  pytorch           
  pytorch-cuda        11.7        h778d358_5                    pytorch
❯ pip list | grep transformers
transformers             4.29.2
```

**Comment by intrepidLi** [comment]
> > Hello, my `transformers` version is 4.29.2, `pytorch` version is 2.0.1+cu117.
> 
> By the way, I am now entirely using your version of `pytorch` and `transformers`, but the same problem arises again. I am trying to understand why this happens...
> 
> Here is my relevant info:
> 
> ```shell
> ❯ pip list | grep torch
> torch                    2.0.1
> torchaudio               2.0.2
> torchvision              0.15.2
> ❯ micromamba list | grep pytorch     
>   pytorch             2.0.1       py3.11_cuda11.7_cudnn8.5.0_0  pytorch           
>   pytorch-cuda        11.7        h778d358_5                    pytorch
> ❯ pip list | grep transformers
> transformers             4.29.2
> ```

Sorry, I also don't know why. When I tried the environment two months ago, it ran normally.  And my trainer.py really has `self.fsdp`. Maybe you can check it again.

<img width="858" alt="屏幕截图 2024-04-24 203714" src="https://github.com/chenchenygu/watermark-learnability/assets/112360222/ac2ca5f1-fd85-480f-9547-44cde560052d">

Plus, I think `fsdp` is only a tool to reduce the consumed memory when GPUs are running. If your training won't throw OOM problem, I think it's OK to edit it.
